ddac/Controllers/BookingsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ddac.Models;
using ddac.ViewModels;

namespace ddac.Controllers
{
    public class BookingsController : Controller
    {
        private UserDBContext db = new UserDBContext();

        // GET: Bookings
        public ActionResult Index()
        {
            return View(db.Bookings.ToList());
        }


        // GET: Bookings/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Booking booking = db.Bookings.Find(id);
            if (booking == null)
            {
                return HttpNotFound();
            }
            return View(booking);
        }

        // GET: Bookings/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Bookings/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "BookingId,Status")] Booking booking)
        {
            if (ModelState.IsValid)
            {
                db.Bookings.Add(booking);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(booking);
        }

        // GET: Bookings/Edit/5
        public ActionResult Edit(int? id)
        {
            //schedule id
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User agent = (User)Session["logged"];
            Schedule schedule = db.Schedules.Find(id);
            if (schedule == null)
            {
                return HttpNotFound();
            }
            TempData["schedule"] = schedule;
            BookingViewModel ScheduleVM = new BookingViewModel
            {
                Schedule = schedule,
                //new SelectList(items, "ItemId", "ItemDetails")
            };

            return View(ScheduleVM);
        }



        // POST: Bookings/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "BookingId,Status")] Booking booking)
        {
            if (ModelState.IsValid)
            {
                db.Entry(booking).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(booking);
        }

        public ActionResult Add(int? id)
        {
            //item id
            Schedule s = (Schedule)TempData["schedule"];
            User a = (User)Session["logged"];
            Item i = db.Items.Find(id);
            Booking NewBooking = new Booking()
            {
                Item = i,
                Schedule = s,
                Agent = a,
                Status = "pending"
            };
            db.Schedules.Attach(s);
            db.Users.Attach(a);
            db.Bookings.Add(NewBooking);
            db.SaveChanges();

            BookingViewModel bvm = new BookingViewModel
            {
                Schedule = s
            };
            return RedirectToAction("Edit", new { id = s.ScheduleId });
        }

        public PartialViewResult _ScheduleList()
        {
            IEnumerable<ScheduleViewModel> model = null;
            model = (from sche in db.Schedules
                     join ship in db.Ships
                     on sche.ShipId equals ship.ShipId
                     select new ScheduleViewModel
                     {
                         Schedule = sche,
                         Ship = ship
                     }
                                 );

            return PartialView(model);

        }

        public PartialViewResult _ItemList(int? id)
        {
            User agent = (User)Session["logged"];
            Schedule schedule = db.Schedules.Find(id);

            var items = db.Items
               .Where(i => i.Source == schedule.Source
               && i.Destination == schedule.Destination)
               .AsEnumerable()
               .ToList();

            var result = items.Where(p => !db.Bookings.Any(p2 => p2.Item.ItemId == p.ItemId));

            return PartialView(result);
        }


        public PartialViewResult _BookingList(int? id)
        {
            var schedule = db.Schedules.Find(id);
            //scheduleid
            var model = db.Bookings
               .Where(b => b.Schedule.ScheduleId == schedule.ScheduleId)
               .AsEnumerable()
               .ToList();

            return PartialView(model);
        }

        // GET: Bookings/Delete/5
        //public ActionResult Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Booking booking = db.Bookings.Find(id);
        //    if (booking == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(booking);
        //}

        // POST: Bookings/Delete/5


        public ActionResult Delete(int? id)
        {
            Schedule s = (Schedule)TempData["schedule"];
            Booking booking = db.Bookings.Find(id);
            db.Bookings.Remove(booking);
            db.SaveChanges();
            return RedirectToAction("Edit", new { id = s.ScheduleId });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ddac/Controllers/ItemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ddac.Models;

namespace ddac.Controllers
{
    public class ItemsController : Controller
    {
        private UserDBContext db = new UserDBContext();

        // GET: Items
        public ActionResult Index()
        {
            return View(db.Items.ToList());
        }

        // GET: Items/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = db.Items.Find(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }

        // GET: Items/AddItem
        public ActionResult AddItem(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer cus = db.Customers.Find(id);
            TempData["customer"] = cus;
            if (cus == null)
            {
                return HttpNotFound();
            }
            //Item item = new Item
            //{
            //    Customer = cus
            //};
            return View(new Item { Customer = cus});
        }

        // POST: Items/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddItem([Bind(Include = "ItemId,ItemName,Weight,Destination,Source")] Item item)
        {
            ModelState.Remove("Status");
            if (ModelState.IsValid)
            {
                    item.Customer = (Customer)TempData["customer"];
                    db.Customers.Attach(item.Customer);
                    db.Items.Add(item);
                    db.SaveChanges();
                    return RedirectToAction("Customer", "Agent");
                
            }

            return View();
        }

        // GET: Items/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = db.Items.Find(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }

        // POST: Items/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ItemId,ItemName,Customer,Weight,Source,Destination")] Item item)
        {
            if (ModelState.IsValid)
            {
                db.Entry(item).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(item);
        }

        // GET: Items/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = db.Items.Find(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }

        // POST: Items/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Item item = db.Items.Find(id);
            db.Items.Remove(item);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ddac/Controllers/ShipsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ddac.Models;

namespace ddac.Controllers
{
    public class ShipsController : Controller
    {
        private UserDBContext db = new UserDBContext();

        // GET: Ships
        public ActionResult Index()
        {
            return View(db.Ships.ToList());
        }

        // GET: Ships/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ship ship = db.Ships.Find(id);
            if (ship == null)
            {
                return HttpNotFound();
            }
            return View(ship);
        }

        // GET: Ships/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Ships/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Ship ship)
        {
            if (ModelState.IsValid)
            {
                db.Ships.Add(ship);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(ship);
        }

        // GET: Ships/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ship ship = db.Ships.Find(id);
            if (ship == null)
            {
                return HttpNotFound();
            }
            return View(ship);
        }

        // POST: Ships/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ShipId,ShipName,IMO")] Ship ship)
        {
            if (ModelState.IsValid)
            {
                db.Entry(ship).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(ship);
        }

        // GET: Ships/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ship ship = db.Ships.Find(id);
            if (ship == null)
            {
                return HttpNotFound();
            }
            return View(ship);
        }

        // POST: Ships/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Ship ship = db.Ships.Find(id);
            db.Ships.Remove(ship);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ddac/Views/Shared/_Layout-Admin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Maersk Line</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
</head>
<body>

    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("CMS", "Index", null, new { @class = "navbar-brand", @style = "margin-left:60px;margin-right:60px" })
            </div>


            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

                
                
                <ul class="nav navbar-nav">
                    <li class="nav-item">
                        @Html.ActionLink("User", "User", "Admin", null, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Ship", "Index", "Ships", null, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Schedule", "Index", "Schedules", null, new { @class = "nav-link" })
                    </li>
                </ul>
                    <ul class="nav navbar-nav mr-md-5 navbar-right">
                        <li>
                            @Html.ActionLink("Logout", "Logout", "Admin", null, new { @class = "nav-link", @style = "margin-right:80px" })
                        </li>
                    </ul>
                
                
            </div>
        </div>
    </nav>


    <div class="container body-content">
        @RenderBody()

        <footer style="bottom:0">
            <hr />
            <p>&copy; @DateTime.Now.Year - Cargo Management System</p>
        </footer>
    </div>


    @RenderSection("scripts", required: false)
</body>
</html>

ddac/Views/Shared/_Layout-Agent.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Maersk Line</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
</head>
<body>

    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("CMS", "Index","Agent",null, new { @class = "navbar-brand", @style = "margin-left:60px;margin-right:60px" })
            </div>


            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

               
                    <ul class="nav navbar-nav">
                        <li class="nav-item">
                            @Html.ActionLink("Customer", "Customer", "Agent", null, new { @class = "nav-link" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Item", "Index", "Items", null, new { @class = "nav-link" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Shipping", "Index", "Bookings", null, new { @class = "nav-link" })
                        </li>
                    </ul>
                    <ul class="nav navbar-nav mr-md-5 navbar-right">
                        <li>
                            @Html.ActionLink("Logout", "Logout", "Admin", null, new { @class = "nav-link", @style = "margin-right:80px" })
                        </li>
                    </ul>
                
            </div>
        </div>
    </nav>


    <div class="container body-content">
        @RenderBody()

        <footer style="bottom:0">
            <hr />
            <p>&copy; @DateTime.Now.Year - Cargo Management System</p>
        </footer>
    </div>


    @RenderSection("scripts", required: false)
</body>
</html>

ddac/Views/Shared/_Layout.cshtml
@model ddac.Models.User

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Maersk Line</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
</head>
<body>

    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("CMS", "Index", null, new { @class = "navbar-brand", @style = "margin-left:60px;margin-right:60px" })
            </div>


            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

                @if (Model.UserType.Equals("admin"))
                {
                    <ul class="nav navbar-nav">
                        <li class="nav-item">
                            @Html.ActionLink("User Management", "User", "Admin", null, new { @class = "nav-link" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Booking Management", "Index", "Bookings", null, new { @class = "nav-link" })
                        </li>
                    </ul>
                    <ul class="nav navbar-nav mr-md-5 navbar-right">
                        <li>
                            @Html.ActionLink("Logout", "Logout", "Admin", null, new { @class = "nav-link", @style = "margin-right:80px" })
                        </li>
                    </ul>
                }
                else if (Model.UserType.Equals("agent"))
                {
                    <ul class="nav navbar-nav">
                        <li class="nav-item">
                            @Html.ActionLink("Customer", "Customer", "Agent", null, new { @class = "nav-link" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Item", "Index", "Agent", null, new { @class = "nav-link" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Vessel", "Index", "Agent", null, new { @class = "nav-link" })
                        </li>
                    </ul>
                    <ul class="nav navbar-nav mr-md-5 navbar-right">
                        <li>
                            @Html.ActionLink("Logout", "Logout", "Admin", null, new { @class = "nav-link", @style = "margin-right:80px" })
                        </li>
                    </ul>
                }
                else
                {
                    <ul class="nav navbar-nav navbar-right">
                        <li class="nav-item">
                            @Html.ActionLink("Login", "Login", "Admin", null, new { @class = "nav-link", @style = "margin-right:80px" })
                        </li>
                    </ul>
                }
            </div>
        </div>
    </nav>


    <div class="container body-content">
        @RenderBody()

        <footer style="bottom:0">
            <hr />
            <p>&copy; @DateTime.Now.Year - Cargo Management System</p>
        </footer>
    </div>


    @RenderSection("scripts", required: false)
</body>
</html>