ddac/Models/Schedule.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ddac.Models
{
    public class Schedule
    {
        
        public int ScheduleId { get; set; }
        [DataType(DataType.DateTime)]
        [Required(ErrorMessage = "Please select a valid departure date")]
        public DateTime? Departure { get; set; }
        [DataType(DataType.DateTime)]
        [Required(ErrorMessage = "Please select a valid arrival date")]
        public DateTime Arrival { get; set; }
        [Required(ErrorMessage = "Please select a valid destination")]
        public Destination? Destination { get; set; }
        [Required(ErrorMessage = "Please select a valid source")]
        public Source? Source { get; set; }
        [Timestamp]
        public Byte[] TimeStamp { get; set; }
        [Required(ErrorMessage = "Please select a valid Ship")]
        public int ShipId { get; set; }
        public decimal Weight { get; set; }

    }

    

    public enum Destination
    {
        Malaysia,
        Thailand,
        Singapore,
        Indonesia,
        Vietnam
    }

    public enum Source
    {
        Malaysia,
        Thailand,
        Singapore,
        Indonesia,
        Vietnam
    }

}

ddac/ViewModels/ScheduleViewModel.cs
using ddac.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ddac.ViewModels
{
    public class ScheduleViewModel
    {
        public Schedule Schedule { get; set; }
        public Ship Ship { get; set; }
    }
}

ddac/Controllers/SchedulesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ddac.Models;

namespace ddac.Controllers
{
    public class SchedulesController : Controller
    {
        private UserDBContext db = new UserDBContext();

        // GET: Bookings
        public ActionResult Index()
        {
            var vm = new User();
            if (Session["logged"] != null)
            {
                vm = (User)(Session["logged"]);
                ViewBag.Message = "Welcome back, " + vm.Username;
            }
            else
                return RedirectToAction("Login", "Admin");
            
            return View(vm);
        }

        public PartialViewResult _ScheduleList()
        {
            return PartialView(db.Schedules.ToList());
        }

        // GET: Bookings/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Schedule booking = db.Schedules.Find(id);
            if (booking == null)
            {
                return HttpNotFound();
            }
            return View(booking);
        }

        // GET: Bookings/Create
        public PartialViewResult _Create()
        { 
            var shiplist = db.Ships
                .AsEnumerable()
                .Select(s => new {
                    s.ShipId,
                    ShipName = string.Format("{0} -- Ship Size {1} KG", s.ShipName, s.IMO)
                })
                .ToList();
            //ViewBag.shipdropdown = new SelectList(shiplist, "ShipId", "ShipName");
            ViewBag.shipdropdown = shiplist;
            return PartialView();
        }


        
        [HttpPost]
        public ActionResult Create(Schedule schedule)
        {
            string imo = db.Ships.Find(schedule.ShipId).IMO.ToString();
            decimal weight = 0;
            if (imo.StartsWith("L")) {
                weight = 28000;
            } else if (imo.StartsWith("M")) {
                weight = 240000;
            }
            else if (imo.StartsWith("S")) {
                weight = 10000;
            }

            if (ModelState.IsValid)
            {
                schedule.Weight = weight;
                db.Schedules.Add(schedule);
                db.SaveChanges();
            }
            return Redirect("Index");


        }

        // GET: Bookings/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Schedule booking = db.Schedules.Find(id);
            var shiplist = db.Ships
                 .AsEnumerable()
                 .Select(s => new {
                     s.ShipId,
                     ShipName = string.Format("{0} -- Ship Size {1} KG", s.ShipName, s.IMO)
                 })
                 .ToList();
            //ViewBag.shipdropdown = new SelectList(shiplist, "ShipId", "ShipName");
            ViewBag.shipdropdown = shiplist;
            if (booking == null)
            {
                return HttpNotFound();
            }
            return View(booking);
        }

        // POST: Bookings/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Departure,Arrival,ShipId,Destination,Source")] Schedule booking)
        {

            var shiplist = db.Ships
                .AsEnumerable()
                .Select(s => new {
                    s.ShipId,
                    ShipName = string.Format("{0} -- Ship Size {1} KG", s.ShipName, s.IMO)
                })
                .ToList();
            //ViewBag.shipdropdown = new SelectList(shiplist, "ShipId", "ShipName");
            ViewBag.shipdropdown = shiplist;

            if (ModelState.IsValid)
            {

                db.Entry(booking).State = EntityState.Added;
                
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(booking);
        }

        // GET: Bookings/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Schedule booking = db.Schedules.Find(id);
            if (booking == null)
            {
                return HttpNotFound();
            }
            return View(booking);
        }

        // POST: Bookings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Schedule booking = db.Schedules.Find(id);
            db.Schedules.Remove(booking);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        

    }
}

ddac/Views/Schedules/Delete.cshtml
@model ddac.Models.Schedule

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Booking</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Departure)
        </dt>

        <dd>
            @Convert.ToString(string.Format("{0:dd/MM/yyyy}", Model.Departure))
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Arrival)
        </dt>

        <dd>
            @Convert.ToString(string.Format("{0:dd/MM/yyyy}", Model.Arrival))
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShipId)
        </dt>

        <dd>
            @("SP" + Model.ShipId.ToString("D4"))
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Destination)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Destination)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Source)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Source)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ddac/Views/Schedules/Details.cshtml
@model ddac.Models.Schedule

@{
    ViewBag.Title = "Details";
    Layout = "/Views/Shared/_Layout-Admin.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Booking</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Departure)
        </dt>

        <dd>
            @Convert.ToString(string.Format("{0:dd/MM/yyyy}", Model.Departure))
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Arrival)
        </dt>

        <dd>
            @Convert.ToString(string.Format("{0:dd/MM/yyyy}", Model.Arrival))
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShipId)
        </dt>

        <dd>
            @("SP" + Model.ShipId.ToString("D4"))
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Destination)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Destination)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Source)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Source)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Weight)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Weight)
        </dd>

    </dl>
</div>
<p>
   
    @Html.ActionLink("Back to List", "Index")
</p>

ddac/Views/Schedules/Edit.cshtml
@model ddac.Models.Schedule

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Schedule</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ScheduleId)

        <div class="form-group">
            @Html.LabelFor(model => model.Departure, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class='input-group date col-md-4' id='datetimepicker1'>
                    @Html.EditorFor(m => m.Departure, new { htmlAttributes = new { @class = "form-control" } })
                    <span class="input-group-addon">
                        <i class="fa fa-calendar"></i>
                    </span>
                </div>
                @Html.ValidationMessageFor(model => model.Departure, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Arrival, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class='input-group date col-md-4' id='datetimepicker2'>
                    @Html.EditorFor(m => m.Departure, new { htmlAttributes = new { @class = "form-control" } })
                    <span class="input-group-addon">
                        <i class="fa fa-calendar"></i>
                    </span>
                </div>
                @Html.ValidationMessageFor(model => model.Arrival, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShipId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.ShipId, new SelectList(ViewBag.shipdropdown, "ShipId", "ShipName"), "Select Ship", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ShipId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Destination, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Destination, "Select shipping destination", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Destination, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Source, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Source, "Select shipping source", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Source, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
@Scripts.Render("~/bundles/datetimepicker")


<script>

    $(function () {
        var today = new Date();
        var tomorrow = new Date(today.getTime() + 24 * 60 * 60 * 1000);
        $('#datetimepicker1').datetimepicker({
            format: 'DD/MM/YYYY',
            minDate: today,
        });

        $('#datetimepicker2').datetimepicker({
            useCurrent: false,
            format: 'DD/MM/YYYY',
            minDate: tomorrow
        });
        $("#datetimepicker1").on("dp.change", function (e) {
            $('#datetimepicker2').data("DateTimePicker").minDate(e.date);
        });
        $("#datetimepicker2").on("dp.change", function (e) {
            $('#datetimepicker1').data("DateTimePicker").maxDate(e.date);
        });
    });

</script>

ddac/Views/Schedules/Index.cshtml
@{
    ViewBag.Title = "Schedule";
    Layout = "/Views/Shared/_Layout-Admin.cshtml";
}

<button class="btn btn-danger" type="button" style="margin:10px"
        data-toggle="modal" data-target="#addModal">
    Add Schedule
</button>

@{  
    Html.RenderAction("_ScheduleList");
}

<div class="modal fade" role="dialog" id="addModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">

                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Add New Schedule</h4>

            </div>
            <div class="modal-body">
                <p>
                    @{
                        Html.RenderAction("_Create");
                    }
                </p>
            </div>

        </div>
    </div>
</div>

ddac/Views/Schedules/_Create.cshtml
@model ddac.Models.Schedule

@using (Html.BeginForm("Create", "Schedules", FormMethod.Post))
{
    @Html.AntiForgeryToken()
<div class="form-horizontal">

    <div class='container-fluid'>
        <div class='form-group row'>
            <div class="col-md-6">
                <label>@Html.LabelFor(model => model.Departure, htmlAttributes: new { @class = "col-md-2 form-control-label" })</label>
                <div class='input-group date col-md-8' id='datetimepicker1'>
                    @Html.EditorFor(m => m.Departure, new { htmlAttributes = new { @class = "form-control" } })
                    <span class="input-group-addon">
                        <i class="fa fa-calendar"></i>
                    </span>
                    @Html.ValidationMessageFor(model => model.Departure, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col-md-6">
                <label>
                    @Html.LabelFor(model => model.Arrival, htmlAttributes: new { @class = "form-control-label col-md-2" })
                </label>
                <div class='input-group date col-md-8' id='datetimepicker2'>
                    @Html.EditorFor(m => m.Arrival, new { htmlAttributes = new { @class = "form-control" } })
                    <span class="input-group-addon">
                        <i class="fa fa-calendar"></i>
                    </span>
                    @Html.ValidationMessageFor(model => model.Departure, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.ShipId, htmlAttributes: new { @class = "form-control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.ShipId, new SelectList(ViewBag.shipdropdown, "ShipId", "ShipName"), "Select Ship", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.ShipId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Source, htmlAttributes: new { @class = "form-control-label col-md-2" })
        <div class="col-md-10">
            @Html.EnumDropDownListFor(model => model.Source, "Select shipping source", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Source, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Destination, htmlAttributes: new { @class = "form-control-label col-md-2" })
        <div class="col-md-10">
            @Html.EnumDropDownListFor(model => model.Destination, "Select shipping destination", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Destination, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-10 col-md-offset-8 ">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary" >Add</button>
        </div>
    </div>

</div>
}

@Scripts.Render("~/bundles/datetimepicker")

<script>

    $(function () {
        var today = new Date();
        var tomorrow = new Date(today.getTime() + 24 * 60 * 60 * 1000);
        $('#datetimepicker1').datetimepicker({
            format: 'DD/MM/YYYY',
            minDate: today,
        });

        $('#datetimepicker2').datetimepicker({
            useCurrent: false,
            format: 'DD/MM/YYYY',
            minDate: tomorrow
        });
        $("#datetimepicker1").on("dp.change", function (e) {
            $('#datetimepicker2').data("DateTimePicker").minDate(e.date);
        });
        $("#datetimepicker2").on("dp.change", function (e) {
            $('#datetimepicker1').data("DateTimePicker").maxDate(e.date);
        });
    });




    //function AddNewBooking() {
    //    var Departure = $('#Departure').val();
    //    var Arrival = $('#Arrival').val();

    //    var Ship = $('#ShipId').val();
    //    var Destination = $('#Destination').val();
    //    var Source = $('#Source').val();

    //    debugger;

    //    if (Departure != "" && Arrival != "" && Destination != "" && Ship != "" != "" && Source != "") {

    //        $.ajax({
    //            type: "POST",
    //            url: "/Schedules/Create",
    //            data: {
    //                Departure: Departure,
    //                Arrival: Arrival,
    //                ShipId:Ship,
    //                Destination: Destination,
    //                Source: Source,
    //            },

    //            success: function () {
    //                alert("Successfully Added");
    //                location.reload();
    //            },
    //            error: function () {
    //                alert("Error");
    //            }
    //        })
    //    }

    //    else {
    //        alert("Please fill up all fields!");
    //    }
    //}
</script>

ddac/Views/Schedules/_ScheduleList.cshtml
@model IEnumerable<ddac.Models.Schedule>

@{
    ViewBag.Title = "Index";
}

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ScheduleId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Departure)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Arrival)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ShipId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Source)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Destination)
        </th>
        <th>
            Weight left
        </th>

        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @("BO" + item.ScheduleId.ToString("D4"))
        </td>
        <td>
            @Convert.ToString(string.Format("{0:dd/MM/yyyy}", item.Departure))
        </td>
        <td>
            @Convert.ToString(string.Format("{0:dd/MM/yyyy}", item.Arrival))

        </td>
        <td>
            @("SP" + item.ShipId.ToString("D4"))

        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Source)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Destination)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Weight)
        </td>

        <td>

            @Html.ActionLink("Details", "Details", new { id = item.ScheduleId }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.ScheduleId })
        </td>
    </tr>
}

</table>